name: Continuous Integration

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            os: ubuntu-20.04
          - ruby: ruby-2.7
            os: ubuntu-20.04

    env:
      RAILS_ENV: test
      WORKING_DIRECTORY: pupilfirst_xapi

    steps:
      - uses: actions/checkout@v2
      - run: test -e Gemfile.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: bin/rspec
        working-directory: ${{ env.WORKING_DIRECTORY }}
